//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeFinanzasPersonales.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaFinanciera
    {
        public int IdMeta { get; set; }
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string TipoMeta { get; set; }
        public decimal MontoObjetivo { get; set; }
        public Nullable<decimal> MontoAcumulado { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaObjetivo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
