//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionDeFinanzasPersonales.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presupuesto
    {
        public int IdPresupuesto { get; set; }
        public int IdUsuario { get; set; }
        public int IdCategoriaPresupuesto { get; set; }
        public decimal Monto { get; set; }
        public int Mes { get; set; }
        public int Año { get; set; }
    
        public virtual CategoriaPresupuesto CategoriaPresupuesto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
